# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instruction

In [ ]:
pip install numpy pandas

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [2]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [3]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/32/95/908d0caa051beae4f7c77652dbbeb781e7b717f3040c5c5fcaed4d3ed08f/numpy-1.26.1-cp312-cp312-win_amd64.whl.metadata
     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.2 kB ? eta -:--:--
     ------------ ------------------------- 20.5/61.2 kB 131.3 kB/s eta 0:00:01
     ------------------------- ------------ 41.0/61.2 kB 195.7 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.2 kB 217.9 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.2 kB 217.9 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.2 kB 217.9 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.2 kB 217.9 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.2 kB 217.9 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.2 kB 217.9 kB/s eta 0:00:01
     -----

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [13]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [14]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [16]:
np.random.rand(2) ##rozkład jednostajny

array([0.59183984, 0.07391709])

In [17]:
np.random.rand(5,5)

array([[0.09102321, 0.79954274, 0.97748222, 0.18885397, 0.37355035],
       [0.29938056, 0.79740112, 0.1953652 , 0.46458815, 0.34797966],
       [0.41144429, 0.68730232, 0.70324074, 0.07955484, 0.39409492],
       [0.53973285, 0.92293579, 0.09091736, 0.07465443, 0.80974172],
       [0.55776771, 0.78579484, 0.72987196, 0.23318849, 0.98712824]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [18]:
np.random.randn(2) ##rozkład normalny

array([-0.6253763 ,  0.53402366])

In [19]:
np.random.randn(5,5)

array([[-0.17358001, -1.50868696,  0.03654444, -1.66194287,  0.3938694 ],
       [-1.31679799, -0.91694149, -0.45241075,  0.27207611, -1.1535728 ],
       [ 1.40706903,  0.55554598, -0.0596638 ,  1.01289327,  0.71088587],
       [ 0.21031873,  1.05895259,  0.43239182, -0.57067554,  0.02274253],
       [ 0.0892291 , -1.16912736,  0.27666302, -1.295845  ,  1.6848023 ]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [20]:
np.random.randint(1,100) # liczba całkowita z przedziału [1,100)

4

In [21]:
np.random.randint(1,100,10) # 10 liczb całkowitych z przedziału [1,100)

array([90, 33, 74, 58, 93, 63, 37, 42, 37, 85])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [22]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [23]:
arr #wektor 25 liczb po kolei

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
ranarr #wektor 10-elementowy losowych wartości od 0 do 50

array([ 7, 11, 32, 40, 40, 40, 35, 42,  2, 38])

## Reshape
Returns an array containing the same data with a new shape.

In [25]:
arr.reshape(5,5) #przekształcanie wektora do macierzy 5,5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [26]:
ranarr

array([ 7, 11, 32, 40, 40, 40, 35, 42,  2, 38])

In [27]:
ranarr.max() #jaka jest maksymalna wartość

42

In [28]:
ranarr.argmax() #na której pozycji jest maksymalna wartość

7

In [ ]:
ranarr.min() #jaka jest minimalna wartość

In [ ]:
ranarr.argmin() #jaka jest pozycja minimalnej wartości

## Shape

Shape is an attribute that arrays have (not a method):

In [29]:
# Vector
arr.shape #jednowymiarowy wektor - 25 wierszy

(25,)

In [30]:
# Notice the two sets of brackets
arr.reshape(1,25) #przkeształcamy na macierz z 1 wierszem i 25 kolumnami

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [31]:
arr.reshape(1,25).shape #i teraz jego wymiary to 1,25 (jeden wiersz i 25 kolumn)

(1, 25)

In [32]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [33]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [34]:
arr.dtype #w arrayach możemy trzymać tylko obiekty jednego typu 

dtype('int32')